//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.0.9,2010;Initial Catalog=QuanLyDoanhThu;Persist Security Info=" +
            "True;User ID=sa;Password=vinhtong")]
        public string QuanLyDoanhThuConnectionString1 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=QuanLyDoanhThu;Integrated Security=True")]
        public string QuanLyDoanhThuConnectionString2 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.0.152,2020;Initial Catalog=QuanLyDoanhThu;User ID=sa;Password=" +
            "vinhtong")]
        public string QuanLyDoanhThuConnectionString3 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=QuanLyDoanhThu;Integrated Security=True")]
        public string QuanLyDoanhThuConnectionString4 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=QuanLyDoanhThu;Integrated Security=True")]
        public string QuanLyDoanhThuConnectionString5 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MSI\\SQLEXPRESS;Initial Catalog=QuanLyDoanhThu;Integrated Security=Tru" +
            "e")]
        public string QuanLyDoanhThuConnectionString6 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.0.9,2010;Initial Catalog=QuanLyDoanhThu;Persist Security Info=" +
            "True;User ID=sa")]
        public string QuanLyDoanhThuConnectionString7 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.0.9,2010;Initial Catalog=QuanLyDoanhThu;User ID=sa")]
        public string QuanLyDoanhThuConnectionString8 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.0.9,2010;Initial Catalog=QuanLyDoanhThu;User ID=sa;Password=vi" +
            "nhtong;TrustServerCertificate=True;")]
        public string QuanLyDoanhThuConnectionString {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.0.9,2010;Initial Catalog=QuanLyDoanhThu;User ID=sa;Password=vi" +
            "nhtong")]
        public string QuanLyDoanhThuConnectionString9 {
            get {
                return ((string)(this["QuanLyDoanhThuConnectionString9"]));
            }
        }
    }
}
